### ISSUE TITLE
CxSystem expects brian connection files even if load_connection set to 0 for every synapse

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#24]
This issue affects the CSV-files already. We have dealt with this issue in simulation configs by commenting out the connections_loading_path_and_filename. If you don't comment it out explicitly, you get an error, see below (*). Now in the GUI you don't have the option of commentng out parameters, so you get this same error if you don't have some connectivity file (even if you don't use the connectivity data later on). 

This is probably the reason I couldn't test the Markram configs. (I can't find any connectivity files for these right now unfortunately!)

Traceback (*):
/home/henhok/PycharmProjects/CxSystem2
 -  Current run filename suffix is: 20191004_10425066
 -  The system is running with euler integration method
 -  CxSystem is running on Python device
 -  Membrane voltages are not initialized.
 -  Default clock is set to 100. us
 -  setting output path ...
Process Process-6:
Traceback (most recent call last):
  File "/home/henhok/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/henhok/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/henhok/PycharmProjects/CxSystem2/CxGUI/CxFront/editor/views.py", line 33, in CxSpawner
    cm =  Cx(anatomy, physiology)
  File "../../CxSystem.py", line 236, in __init__
    self.configuration_executor()
  File "../../CxSystem.py", line 268, in configuration_executor
    self.parameter_to_method_mapping[self.anat_and_sys_conf_df.loc[self.value_line_idx, 0]][1]()
  File "../../CxSystem.py", line 428, in set_runtime_parameters
    self.parameter_to_method_mapping[parameter][1](self.current_values_list[ParamIdx])
  File "../../CxSystem.py", line 518, in _set_load_brian_data_path
    ' -  The brian_data file cannot be found for loading'
AssertionError:  -  The brian_data file cannot be found for loading

**Comment by henhok** [comment]
Default behavior should be: if no connectivity file given, create connections.

**Comment by Vafa-Andalibi** [comment]
This is now fixed in ff83876dfa7f35241844d1bd3cc9b067e7e618ee, the default behavior is now changed to this: 
- If connections `load_connection` flag is set, then the connection file will be loaded. 
- If `load_position_only` is set, then the connection file will be loaded. 
- If file doesn't exists in the above scenarios error will raise because I thought it might confuse the user specially when the stdout is not checked, e.g. cluster run, so the user thinks the connections are being loaded from file whereas the file actually doesn't exist and the connections are being generated. 
- If neither of the above flags are set, no error will be raised even if the file doesn't exist

Also for the record, the commenting is now available via putting the `#` in front of the value instead of the variable name. For instance: 

```
#load_positions_only
1
```

does not work now in GUI because the variable names should be consistent on the server, but in case you need to comment it, this will do the job: 

```
load_positions_only
#1
```
