### ISSUE TITLE
Simulations fail to run when there's nothing to arrayrun?

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#64]
Tried running COBAEIF without the curly braces in physio parameter k. So instead of { ... }, just one number like 3. The job is submitted fine and in terminal it says:

2019-11-25 08:20:49,351 info_logger  INFO     User  started simulation
PID:  10354

but then nothing comes after that.

**Comment by Vafa-Andalibi** [comment]
Is this in http or https?

**Comment by Vafa-Andalibi** [comment]
This is an expected behavior. The server in https mode does not print out the simulation log because the user won't be able to see it , instead it keeps it in a file in users' workspace. Then when you click on `simulations` it will show the tail of that output. This way the user can follow how much of the current simulation(s) is done already.
